<a href="https://colab.research.google.com/github/nandishmadhu/sentence_embedding/blob/master/SQLiteDB_Storing_Retrieving_Vectors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import sqlite3
import numpy as np

In [2]:
#create a connection to the SQLite DB
conn=sqlite3.connect("vectordb.db")
#Create a cursor object to execute SQL commands
cursor=conn.cursor()

In [3]:
#Create a table for vector data
cursor.execute(
    """
    CREATE TABLE IF NOT EXISTS vectors (
      id INTEGER PRIMARY KEY,
      vector BLOB NOT NULL
    )
    """
)

In [17]:
#generate some sample vectors
vect1=np.array([1.2,3.4,2.1,0.8])
vect2=np.array([2.7,1.5,3.9,2.3])

In [18]:
vect1

array([1.2, 3.4, 2.1, 0.8])

In [19]:
vect2

array([2.7, 1.5, 3.9, 2.3])

In [5]:
vect1.tobytes() # numpy array to bytestream

b'333333\xf3?333333\x0b@\xcd\xcc\xcc\xcc\xcc\xcc\x00@\x9a\x99\x99\x99\x99\x99\xe9?'

In [6]:
#Insert vector data into table
cursor.execute("INSERT INTO vectors (vector) VALUES (?)",
               (sqlite3.Binary(vect1.tobytes()),))

In [9]:
cursor.execute("INSERT INTO vectors (vector) VALUES (?)",
               (sqlite3.Binary(vect2.tobytes()),))

In [10]:
#Retrieve data
cursor.execute("SELECT vector FROM vectors")

In [11]:
rows=cursor.fetchall()

In [12]:
rows

[(b'333333\xf3?333333\x0b@\xcd\xcc\xcc\xcc\xcc\xcc\x00@\x9a\x99\x99\x99\x99\x99\xe9?',),
 (b'\x9a\x99\x99\x99\x99\x99\x05@\x00\x00\x00\x00\x00\x00\xf8?333333\x0f@ffffff\x02@',)]

In [13]:
vector=np.frombuffer(rows[0][0],dtype=np.float64)

In [14]:
vector

array([1.2, 3.4, 2.1, 0.8])

In [15]:
vectors=[]
for row in rows:
    vector=np.frombuffer(row[0],dtype=np.float64)
    vectors.append(vector)

In [16]:
vectors

[array([1.2, 3.4, 2.1, 0.8]), array([2.7, 1.5, 3.9, 2.3])]

**Vector Similarity Search (VSS)**

In [20]:
query_vect=np.array([1.0,3.2,2.0,0.5])

In [21]:
cursor.execute("""
SELECT vector FROM vectors ORDER BY abs(vector - ?) ASC
""",(sqlite3.Binary(query_vect.tobytes()),))

In [22]:
res=cursor.fetchone() # finding the top one

In [25]:
np.frombuffer(res[0], dtype=np.float64) # most similar vector

array([2.7, 1.5, 3.9, 2.3])